### ISSUE TITLE
hnysqlx: missing fields when using existing prepared statements within a transaction

### ISSUE THREAD

**Issue by eminano** [honeycombio/beeline-go#100]
Hi! 

When using the honeycomb sqlx wrapper, and using an existing prepared statement from a transaction, it seems the prepared statement tracing fields are lost (i.e., ```db.query```). 

After digging a bit in the implementation of the honeycomb sqlx wrapper it seems the reason for this to happen is that the fields are added to the prepared statement object builder:
https://github.com/honeycombio/beeline-go/blob/master/wrappers/hnysqlx/sqlx.go#L539

But when calling a prepared statement from a transaction, the transaction builder is used instead (which lacks fields such as the ```db.query```):
https://github.com/honeycombio/beeline-go/blob/master/wrappers/hnysqlx/sqlx.go#L1824-L1828

This would mean the original prepared statement fields are lost from that point on.

Here's a simplified code snippet illustrating the issue:
```
struct object {
     ID string `db:"id"`
     UpdatedAt time `db:"updated_at"`
}

func reproduceIssue() error {
	db, err := sqlx.Open("postgres", uri)
	if err != nil {
		return err
	}

	wdb := hnysqlx.WrapDB(db)

	query := "UPDATE my_table SET updated_at = now() where id = :id RETURNING updated_at"
	// prepare a statement 
	if updateStmt, err = wdb.PrepareNamed(query)); err != nil {
		return err
	}

	o := &object{ ID: "id-1" }

       // This query will have a `db.query` field in the trace
	if err := updateStmt.QueryRowContext(ctx, o).Scan(&o.UpdatedAt); err != nil {
		return err
	}

	// open a transaction that uses the prepared statement
	tx, err := wdb.BeginTxx(context.Background(), nil)
	if err != nil {
		return err
	}

	// This query won't have a `db.query` field in the trace
	if err := tx.NamedStmt(updateStmt).QueryRowContext(ctx, o).Scan(&o.UpdatedAt); err != nil {
		tx.Rollback()
		return err
	}

	return tx.Commit()
}
```

Note: the scenario where I've encountered the issue is with ```NamedStmt```, however I think it might also apply to ```Stmt```. I found it suspicious that the ```db.query``` field isn't added to the ```db.Preparex``` call when it is done for the ```db.PrepareNamed```.
https://github.com/honeycombio/beeline-go/blob/master/wrappers/hnysqlx/sqlx.go#L577

Also, this seems to be handled properly for the cases where a prepared statement is created from a transaction, but not when an existing prepared statement is used from a transaction. 
https://github.com/honeycombio/beeline-go/blob/master/wrappers/hnysqlx/sqlx.go#L1884

Hope this is clear!

Thanks in advance,
Esther

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
