### ISSUE TITLE
Propagation Header not being processed in Lambda APIs using HTTP Middleware

### ISSUE THREAD

**Issue by wolfeidau** [honeycombio/beeline-go#147]
I am having trouble understanding why header propagation needs is happening only at the start of a trace, is this a requirement of the API or the data model?

https://github.com/honeycombio/beeline-go/blob/fc191178794e624655ce773ca000b04d5160474b/wrappers/common/common.go#L57-L83

My use case is that we have an AWS Lambda function, which accepts API calls and we establish the trace when the event hits the lambda, then we pass it through a layer which translates it into a HTTP request, and onto the honeycombe echo middleware.

When this middleware runs there is already a span active, so it doesn't read the propagation header.

If there is already a span running, can you link in the propagation from another source later?

Cheeres

**Comment by MikeGoldsmith** [comment]
Hey @wolfeidau - thanks for raising the question.

Trace context propagation is expected to only happen on process boundaries and doesn't support linking traces together directly.

**Span Links**
There is the idea of Span Links, which does allow spans from different traces to be associated but I think you'd prefer for these spans to form one continuous trace.

However, the Beelines do not currently support creating [span links](https://docs.honeycomb.io/getting-data-in/tracing/send-trace-data/#links) but is something we may add in the future. Note that the OpenTelemetry SDK combined with the Honeycomb exporter does support Span Links.

**Creating your trace using the propagation**
If you manually create the trace in your AWS function and have access to the http headers before it translates it into an HTTP request, you could invoke the propagation function directly to create the trace object in the root span to represent your Lambda func and it will inherit the propagated trace ID to tie everything together.

If you're using the defualt honeycomb HTTP headers, there is a super simple way to do it:
```go
ctx := context.Background()
header := "honeycomb-header-value"
trace := trace.NewTrace(ctx, header)
```
[trace.NewTrace](https://github.com/honeycombio/beeline-go/blob/main/trace/trace.go#L112)

If you're using another header format, you'll need to extract the PropagationContext first and then create the trace.
```go
ctx := context.Background()
headers =: map[string]string{"X-Honeycomb-Trace": "honeycomb-header-value"}
propCtx, err := propagation.UnmarshalW3CTraceContext(headers) //note this takes a map[string]string
trace := trace.NewTraceFromPropagationContext(ctx, propCtx)
```
[propagation.UnmarshalW3CTraceContext](https://github.com/honeycombio/beeline-go/blob/main/propagation/w3c.go#L51)
[trace.NewTraceFromPropagationContext](https://github.com/honeycombio/beeline-go/blob/main/trace/trace.go#L59)

**Comment by wolfeidau** [comment]
@MikeGoldsmith thanks a lot, we are testing this at the moment with our project.

I will get something out soon with an example to just to complete the conversation.

**Comment by wolfeidau** [comment]
If anyone tries to use this value for testing, don’t it is invalid https://github.com/honeycombio/beeline-go/blob/d049d15f65f5982c4f7591b213cc419bc5d6d57e/propagation/honeycomb.go#L25 and will get silently ignored 😞 

Was very confusing writing tests and having propagation not work.

**Comment by MikeGoldsmith** [comment]
Do you mean the example trace header was being silently ignored? Interesting, I'll take a look and update it to something that should work.

**Comment by wolfeidau** [comment]
@MikeGoldsmith yeah exactly, as soon as i used a beeline client and copied the trace id to use for testing it worked 👍 and was quite different length wise. I started digging into the beeline/libhoney code and spotted some validation but didn't go as far as vendoring and adding print statements 😅

Thanks for follow up BTW.

**Comment by MikeGoldsmith** [comment]
Thanks for confirming 👍
