### ISSUE TITLE
Error when running go get -u github.com/honeycombio/beeline-go/..

### ISSUE THREAD

**Issue by jalevin** [honeycombio/beeline-go#154]
New to honeycomb.io. 

Running `go get -u github.com/honeycombio/beeline-go/...`

`go: github.com/go-playground/validator/v10 upgrade => v10.4.1
go: github.com/gobuffalo/validate/v3 upgrade => v3.3.0
go: github.com/Masterminds/semver/v3 upgrade => v3.1.0
go: github.com/jackc/pgproto3/v2 upgrade => v2.0.5
go: github.com/mattn/go-colorable upgrade => v0.1.8
go: github.com/modern-go/reflect2 upgrade => v1.0.1
go: github.com/gobuffalo/packd upgrade => v1.0.0
go: github.com/json-iterator/go upgrade => v1.1.10
go: github.com/gofrs/uuid upgrade => v3.3.0+incompatible
go: github.com/golang/protobuf upgrade => v1.4.3
go: github.com/gobuffalo/fizz upgrade => v1.13.0
go: github.com/gobuffalo/nulls upgrade => v0.4.0
go: github.com/jackc/chunkreader/v2 upgrade => v2.0.1
go: golang.org/x/sys upgrade => v0.0.0-20201026173827-119d4633e4d1
go: go.opentelemetry.io/contrib/propagators upgrade => v0.13.0
go: gopkg.in/yaml.v2 upgrade => v2.3.0
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/gobuffalo/flect upgrade => v0.2.2
go: google.golang.org/protobuf upgrade => v1.25.0
go: golang.org/x/crypto upgrade => v0.0.0-20201016220609-9e8e0b390897
go: golang.org/x/sync upgrade => v0.0.0-20201020160332-67f06af15bc9
go: github.com/gobuffalo/helpers upgrade => v0.6.1
go: golang.org/x/text upgrade => v0.3.3
go: github.com/ugorji/go/codec upgrade => v1.1.13
go: github.com/gobuffalo/pop/v5 upgrade => v5.3.1
go: github.com/rogpeppe/go-internal upgrade => v1.6.2
go: github.com/jackc/pgservicefile upgrade => v0.0.0-20200714003250-2b9c44734f2b
go: golang.org/x/net upgrade => v0.0.0-20201026091529-146b70c837a4
go: github.com/modern-go/concurrent upgrade => v0.0.0-20180306012644-bacd9c7ef1dd
go: github.com/pkg/errors upgrade => v0.9.1
go: github.com/jackc/pgconn upgrade => v1.7.0
go: github.com/mattn/go-sqlite3 upgrade => v1.14.4
go: github.com/vmihailenco/tagparser upgrade => v0.1.2
go: github.com/jackc/pgtype upgrade => v1.5.0
go: github.com/sergi/go-diff upgrade => v1.1.0
go: go.opentelemetry.io/otel upgrade => v0.13.0
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: github.com/gobuffalo/envy upgrade => v1.9.0
go: google.golang.org/appengine upgrade => v1.6.7
go: github.com/microcosm-cc/bluemonday upgrade => v1.0.4
go: github.com/jackc/pgx/v4 upgrade => v4.9.0
go: github.com/go-sql-driver/mysql upgrade => v1.5.0
go: github.com/julienschmidt/httprouter upgrade => v1.3.0
go: github.com/valyala/fasttemplate upgrade => v1.2.1
go: github.com/gobuffalo/tags/v3 upgrade => v3.1.0
go: github.com/klauspost/compress upgrade => v1.11.1
 # github.com/honeycombio/beeline-go/propagation
../../../go/pkg/mod/github.com/honeycombio/beeline-go@v0.8.0/propagation/b3.go:33:32: propagator.GetAllKeys undefined (type b3.B3 has no field or method GetAllKeys)
../../../go/pkg/mod/github.com/honeycombio/beeline-go@v0.8.0/propagation/w3c.go:31:16: undefined: propagators.DefaultHTTPPropagator
../../../go/pkg/mod/github.com/honeycombio/beeline-go@v0.8.0/propagation/w3c.go:55:16: undefined: propagators.DefaultHTTPPropagator
`

This prevents the app from building or running

**Comment by emorikawa** [comment]
I also have this problem.

**Comment by martin308** [comment]
@jalevin @emorikawa using `go get -u` will tell go to also update dependencies which will cause this. We have some instructions on installing the beeline over here https://docs.honeycomb.io/getting-data-in/go/beeline-tutorial/#install-the-go-beeline. Let me know if this helps

**Comment by jalevin** [comment]
@martin308 thank you for the response. 

The confusion is coming because as new users we are getting referred to this blog post: https://www.honeycomb.io/blog/instrument-your-go-app-in-minutes-with-the-honeycomb-beeline-for-go/. 

I've also been referred to that docs page via the support team on Intercom.

At first glance, the tutorial you're referring us to is not great. What I like about the blog post is that it shows me how to instrument my existing app, while this other project is asking me to clone an existing project and build it, which I don't want to do.

In hindsight I can see that you're referring to the examples directory which is fine, but it would help out to update the example blog post (which I am referred to by https://www.honeycomb.io/auto-instrumentations/ ).

On the docs page also, explicitly say tell me the purpose of cloning and building that project in the first code blurb AND write out the directory of the examples I'm going to be working from in that repo up near the first code blurb  `beeline-go/examples/nethttp/main.go`

![image](https://user-images.githubusercontent.com/1669620/97501208-c4bae880-1925-11eb-9a38-37d96b2ba4bc.png)

Also, do I need to explicitly build beeline or can I just `go get` ? 

That should be included as well.

Hope this helps.

**Comment by martin308** [comment]
@jalevin thanks for pointing me to the blog post, I'll go and fix it up now. You can use the originally listed command, you just need to drop the `-u` so that go doesn't try to update all of the dependencies at the same time

**Comment by martin308** [comment]
Please re-open this if you're still having issues!
