### ISSUE TITLE
Debug mode is partially broken and does not print responses from the honeycomb API

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/beeline-go#175]
I ran into this while trying to debug why some events were silently being dropped and not making it into honeycomb.

It seems that when you set `Config{Debug: true}` beeline starts a goroutine to read responses from libhoney transmission's response channel, so that they can be logged to stdout:

https://github.com/honeycombio/beeline-go/blob/a3ac12a9728fb22cd61e9c31f107585603f39a46/beeline.go#L167-L170

`client.TxResponses()` is a reference to the `client` package in this beeline module. It seems as though the package is setup to provide safe zero values if a client hasn't yet been configured, but the `TxResponses()` helper is broken - it always returns the safe zero value, even if the client has been configured (note the missing `return` on line 53):

https://github.com/honeycombio/beeline-go/blob/a3ac12a9728fb22cd61e9c31f107585603f39a46/client/client.go#L51-L59

This means `beeline.Init()` function is receiving a closed channel, and never prints any of the responses to STDOUT.

One other thing that jumped out at me is that because the `client` variable is initialized with an empty `libhoney.Client{}`, the "safe zero value" behaviour for `client.NewBuilder()` is never called. If you change `client` to default to nil, the test suite panics at the point where it tries to send an event created from the zero value builder (line 16):

https://github.com/honeycombio/beeline-go/blob/a3ac12a9728fb22cd61e9c31f107585603f39a46/client/client_test.go#L13-L16

**Comment by nathanleclaire** [comment]
ping @paulosman @vreynolds

**Comment by nathanleclaire** [comment]
Thanks for filing @BRMatt !

**Comment by robbkidd** [comment]
@honeycombio/integrations-team 👀

**Comment by MikeGoldsmith** [comment]
This is not something we are planning to do in the near term as we are focused on improving our integration and support of OpenTelemetry tooling. We would welcome a PR to help resolve the problem.
