### ISSUE TITLE
internal.ResponseWriter doesn't implement http.Hijacker

### ISSUE THREAD

**Issue by geotho** [honeycombio/beeline-go#18]
Hello! Thanks for the Go libraries – they're very useful.

In our API server, we create a `gorilla.Mux` that routes to both HTTP endpoints and Websocket endpoints. The Websocket endpoints use a [`websocket.Upgrader`](https://godoc.org/github.com/gorilla/websocket#Upgrader.Upgrade).

Unfortunately, Beeline's `internal.ResponseWriter` doesn't implement `http.Hijacker`, which the websocket upgrader requires. So we can't use Beeline for those endpoints.

We're working around the issue by only piping the HTTP handlers through the supplied Gorilla middleware, but it would be great if it worked (or at least didn't break) our websocket endpoints.

We've previously used https://github.com/felixge/httpsnoop to do this for our websocket endpoints, and it looks like you used to also. Though I understand why you might want to reduce your number of third-party dependencies.

Thanks again!

**Comment by maplebed** [comment]
Thanks for bringing this up! We are ok using the httpsnoop library. I had hoped that by using the `httpsnoop.Wrap` function, everything would just work. :( I don't have a websocket example handy; you don't happen to have a small buildable application that shows how this fails you, do you? I am happy to try and get this working! 

I'm curious though, how you would like the beeline to behave in the face of the HTTP request getting hijacked. Normally the beeline has access to run code before the wrapped handler starts and after it finishes. It looks like a hijack wrapper would get to run before the rest of the code, but not after. Do you have any insight into what a useful thing for the beeline to do when the connection gets hijacked? (aside from break everything, of course. ;) )

Thanks!

**Comment by geotho** [comment]
Hi Ben,

Sorry for the delay getting back to you.

I've added a failing test case in my fork here:
https://github.com/geotho/beeline-go/blob/websocket-failing-test/internal/internal_test.go#L43-L86

If you comment out the line which wraps the `http.ResponseWriter` in an `internal.ResponseWriter` (https://github.com/geotho/beeline-go/blob/websocket-failing-test/internal/internal_test.go#L49-L50) you should see the test passes.

I don't there's a huge amount of useful stuff beeline can do in the case of hijacked connections. For us, just counting the request and recording the path would still be useful. Potentially you might also get a response code (which I think is 101 for changing protocol?)

I'm happy to PR a fix if we agree on a backwards compatible approach? Though I'll admit I'm still not 100% clear on why this *doesn't* work.

**Comment by maplebed** [comment]
Thanks for the example! I’ll dig around a bit and see what I can find.
