### ISSUE TITLE
propagation imports go.opentelemetry.io/otel/label which has been removed

### ISSUE THREAD

**Issue by crewjam** [honeycombio/beeline-go#197]
```
$  go get -u ./...
# ...
	github.com/honeycombio/beeline-go/propagation imports
	go.opentelemetry.io/otel/label: cannot find module providing package go.opentelemetry.io/otel/label
```

**Comment by crewjam** [comment]
Possibly related? https://github.com/honeycombio/beeline-go/pull/195

**Comment by vreynolds** [comment]
Tracking upgrade in #200 -- we're hoping to get a GA OTEL release soon, so we can confidently bump the beeline and not get additional breaking changes afterwards
