### ISSUE TITLE
Tag for version v1.1.3 has a typo.

### ISSUE THREAD

**Issue by maximelb** [honeycombio/beeline-go#248]
The tag should be `v1.1.3` but it is `v.1.1.3`.

Took me a while to figure out why I could not `go get` at 1.1.3.

**Comment by MikeGoldsmith** [comment]
Thanks for catching this @maximelb - I think this fixed up ASAP.

**Comment by MikeGoldsmith** [comment]
All fixed - the [v1.1.3](https://github.com/honeycombio/beeline-go/releases/tag/v1.1.3) tag is now up and release moved to that tag 👍🏻  

Thanks again @maximelb!
