### ISSUE TITLE
hnysql wrapping strategy limits interoperability

### ISSUE THREAD

**Issue by irl-segfault** [honeycombio/beeline-go#255]
The `hysql.DB` type does not embed a *sql.DB, and therefore is a not a drop-in replacement.  This means users of hnysql are not easily able to integrate with any libraries or code that expects a type of *sql.DB. 

The comment says	
```
	// wdb is the wrapped sql db. It is not embedded because it's better to fail
	// compilation if some methods are missing than it is to silently not
	// instrument those methods. If you believe that this wraps all methods, it
	// would be reasonable to think that calls that don't show up in Honeycomb
	// aren't happening when they are - they just fell through to the underlying
	// *sql.DB. So all methods present on *sql.DB are recreated here, but as the
	// wrapped package changes, we will fail to compile against apps using those
	// new features and need a patch.
```

I understand the motivation here, but it does severely limit the usability of this package.  For example, the popular [sqlx](https://github.com/jmoiron/sqlx/blob/master/sqlx.go#L240) package embeds the stdlib type, and therefore can be used as a drop-in replacement.

Opening this issue to request an implementation that does embed the stdlib type so that we can integrate with existing code easily.

**Comment by MikeGoldsmith** [comment]
Hey @irl-segfault 

Thanks for creating the issue. We understand your request and will add it to our backlog for consideration.

**Comment by irl-segfault** [comment]
I did some more experimentation with this, and I don't think it's possible with Go's type system to wrap the *sql.DB, either via embedding *sql.DB, composing *sql.DB, or embedding the sql interfaces and still play nicely with the type system due to the fact that sql methods return concrete types and not interfaces.  Looks like most of the instrumentation out there wraps the sql drivers to get around this -- see https://github.com/XSAM/otelsql.  
Closing this out
