### ISSUE TITLE
perf: "app." + key is allocating new objects still

### ISSUE THREAD

**Issue by lizthegrey** [honeycombio/beeline-go#401]
**Versions**

- Go: 1.21.4
- Beeline: 1.13.0

**Steps to reproduce**

1. Run shepherd at high volume ;)
2. Look at the profiles.
3. Weep.

![Screenshot from 2023-11-22 10-04-31](https://github.com/honeycombio/beeline-go/assets/614704/d5c5ec9e-64ce-4595-aef3-55d3e295ada8)

**Additional context**
#328 tried to make this better (before, we were using sprintf which is worse ugh), but it's now 7% of our allocations. This is not good. We probably would save time using a LRU cache for mapping foo to app.foo to avoid allocating brand new strings every time.

**Comment by robbkidd** [comment]
Another contender for a memory improvement when adding fields: #406
