### ISSUE TITLE
echo example creates a binary that shadows sh `echo` builtin

### ISSUE THREAD

**Issue by brandonbloom** [honeycombio/beeline-go#78]
Please consider renaming the directory that the echo example is in. As it is, experimenting with beeline-go caused `$GOPATH/bin/echo` to shadow `/bin/echo` in totally unrelated configure scripts & makefiles. The behavior was extremely surprising and confusing.

The offending file:
https://github.com/honeycombio/beeline-go/blob/9adb5c235b865f43dd103e11ceb5d45ceb05c4e1/examples/echo/main.go

I originally reported this, erroneously, as an issue with the Echo framework. More details over there: https://github.com/labstack/echo/issues/1408

**Comment by maplebed** [comment]
🔥 most excellent suggestion. I can only imagine the level of wtf that must have lead up to correctly filing this error. Thank you!

**Comment by brandonbloom** [comment]
Yup.... "why is this ./configure taking forever? ... _echo_ is stalled? WTF?" .... many minutes ...then  this ticket
